-- ESign Lab: tables of the ESIGN schema (run as ESIGN, or with current_schema = ESIGN)

-- Settings (name/value). DEV_MODE = Y shows signing links and one-time codes on screen,
-- for instances without a mail server.
create table esign_settings (
    name   varchar2(50)   not null primary key,
    value  varchar2(4000),
    note   varchar2(400)
);

insert into esign_settings (name, value, note) values ('ORG_NAME', 'ESign Lab', 'Shown in e-mails and on the certificate page');
insert into esign_settings (name, value, note) values ('FROM_EMAIL', 'no-reply@example.com', 'Sender address of all e-mails');
insert into esign_settings (name, value, note) values ('DEV_MODE', 'Y', 'Y = show signing links and one-time codes on screen (no mail server)');
insert into esign_settings (name, value, note) values ('LINK_TTL_DAYS', '14', 'Days a signing link stays valid');
insert into esign_settings (name, value, note) values ('OTP_TTL_MINUTES', '10', 'Minutes a one-time code stays valid');
insert into esign_settings (name, value, note) values ('OTP_MAX_ATTEMPTS', '5', 'Wrong codes allowed before a new code is needed');
insert into esign_settings (name, value, note) values ('MAX_PDF_MB', '20', 'Largest PDF accepted');
insert into esign_settings (name, value, note) values ('SIGN_APP', 'ESIGN-SIGN', 'Alias of the public signing application');

-- Demo mailbox: with DEV_MODE = Y, e-mails are captured here instead of being sent
create table esign_dev_outbox (
    mail_id      number generated by default on null as identity primary key,
    doc_id       number,
    signer_id    number,
    to_email     varchar2(320) not null,
    subject      varchar2(4000),
    body_html    clob,
    link_url     varchar2(4000),
    otp_code     varchar2(6),
    has_attachment varchar2(1) default on null 'N' not null,
    created_on   timestamp with time zone default on null systimestamp not null
);
create index esign_dev_outbox_doc_ix on esign_dev_outbox (doc_id, mail_id);

-- Envelopes: one PDF sent to one or more signers
create table esign_documents (
    doc_id           number generated by default on null as identity primary key,
    envelope_id      varchar2(36)   not null unique,
    title            varchar2(200)  not null,
    message          varchar2(4000),
    file_name        varchar2(400),
    original_pdf     blob,
    original_sha256  varchar2(64),
    page_count       number,
    signed_pdf       blob,
    signed_sha256    varchar2(64),
    status           varchar2(20)   default on null 'DRAFT' not null
                     constraint esign_documents_status_ck
                     check (status in ('DRAFT', 'SENT', 'COMPLETED', 'DECLINED', 'VOIDED')),
    routing          varchar2(10)   default on null 'SEQUENTIAL' not null
                     constraint esign_documents_routing_ck check (routing in ('SEQUENTIAL', 'PARALLEL')),
    expires_on       timestamp with time zone,
    created_by       varchar2(255)  not null,
    created_on       timestamp with time zone default on null systimestamp not null,
    sent_on          timestamp with time zone,
    completed_on     timestamp with time zone,
    void_reason      varchar2(4000)
);

-- Recipients of an envelope. Only hashes of the signing token and of the one-time code are stored.
create table esign_signers (
    signer_id              number generated by default on null as identity primary key,
    doc_id                 number not null
                           constraint esign_signers_doc_fk references esign_documents on delete cascade,
    sign_order             number default on null 1 not null,
    signer_name            varchar2(200) not null,
    signer_email           varchar2(320) not null,
    stamp_page             varchar2(10)  default on null 'LAST' not null
                           constraint esign_signers_page_ck check (stamp_page in ('LAST', 'FIRST', 'NONE')),
    stamp_position         varchar2(20)  default on null 'BOTTOM_RIGHT' not null
                           constraint esign_signers_pos_ck check (stamp_position in
                               ('BOTTOM_LEFT', 'BOTTOM_CENTER', 'BOTTOM_RIGHT', 'TOP_LEFT', 'TOP_RIGHT')),
    status                 varchar2(20)  default on null 'PENDING' not null
                           constraint esign_signers_status_ck
                           check (status in ('PENDING', 'SENT', 'VIEWED', 'SIGNED', 'DECLINED', 'VOIDED')),
    token_hash             varchar2(64)  constraint esign_signers_token_uk unique,
    token_expires          timestamp with time zone,
    otp_hash               varchar2(64),
    otp_expires            timestamp with time zone,
    otp_attempts           number default on null 0 not null,
    otp_verified_on        timestamp with time zone,
    viewed_on              timestamp with time zone,
    signature_png          blob,
    signature_method       varchar2(10)
                           constraint esign_signers_method_ck check (signature_method in ('DRAWN', 'TYPED')),
    consent_text           varchar2(1000),
    consent_on             timestamp with time zone,
    signed_on              timestamp with time zone,
    signed_ip              varchar2(64),
    signed_user_agent      varchar2(1000),
    doc_sha256_at_signing  varchar2(64),
    decline_reason         varchar2(4000),
    constraint esign_signers_email_uk unique (doc_id, signer_email)
);
create index esign_signers_doc_ix on esign_signers (doc_id, sign_order);

-- Audit trail: an immutable table (rows can't be updated, and not deleted for 16 days), with each
-- row chained to the previous row of the same envelope by SHA-256.
create sequence esign_audit_seq;

create immutable table esign_audit (
    audit_id     number        not null,
    doc_id       number        not null,
    signer_id    number,
    event_type   varchar2(40)  not null,
    details      varchar2(4000),
    actor        varchar2(320),
    ip_address   varchar2(64),
    user_agent   varchar2(1000),
    event_time   timestamp     not null,          -- UTC
    prev_hash    varchar2(64),
    row_hash     varchar2(64)  not null,
    constraint esign_audit_pk primary key (audit_id)
) no drop until 0 days idle
  no delete until 16 days after insert;
create index esign_audit_doc_ix on esign_audit (doc_id, audit_id);

-- The certificate and private key that seal completed PDFs (PKCS#7 digital signature).
-- Lab setup: a self-signed certificate. Production: a certificate from a CA, key in a wallet/HSM.
create table esign_seal_keys (
    seal_id           number generated by default on null as identity primary key,
    label             varchar2(200) not null,
    subject           varchar2(400),
    cert_der          blob          not null,
    private_key_b64   clob          not null,
    valid_from        date,
    valid_to          date,
    is_active         varchar2(1) default on null 'Y' not null
                      constraint esign_seal_keys_active_ck check (is_active in ('Y', 'N'))
);

-- Report view for the application
create or replace view esign_documents_v as
select d.doc_id,
       d.envelope_id,
       d.title,
       d.file_name,
       d.status,
       d.routing,
       d.page_count,
       d.created_by,
       d.created_on,
       d.sent_on,
       d.completed_on,
       d.expires_on,
       d.original_sha256,
       d.signed_sha256,
       (select count(*) from esign_signers s where s.doc_id = d.doc_id) as signers,
       (select count(*) from esign_signers s where s.doc_id = d.doc_id and s.status = 'SIGNED') as signed,
       case d.status
           when 'COMPLETED' then 'u-success'
           when 'SENT'      then 'u-info'
           when 'DECLINED'  then 'u-danger'
           when 'VOIDED'    then 'u-danger'
           else 'u-color-14'
       end as status_class
  from esign_documents d;
